DROP TABLE products

CREATE TABLE IF NOT EXISTS products (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) NOT NULL DEFAULT 'product',
    price NUMERIC(8, 2) NOT NULL DEFAULT 0,
    quantity INTEGER NOT NULL DEFAULT 0
)